spring.application.name=projeck_cuoi_mon

spring.datasource.url=jdbc:mysql://localhost:3306/smart_academic_lab?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=never
server.servlet.session.timeout=30m
spring.thymeleaf.cache=false
